import { Products } from './app/shared/models/Products';

export const sample_Products: Products[] = [
  {
    id: '1',
    name: 'Potato',
    category: 'Fresh Vegetables',
    tag: 'Vegetables & Fruits',
    favorite: false,
    price: 35,
    weight: '1 kg',
    quantity: 10,
    image: './assets/Vegetables&Fruits/FreshVegetables/potato.jpg',
    hey: false,
  },
  {
    id: '2',
    name: 'Tomato',
    category: 'Fresh Vegetables',
    tag: 'Vegetables & Fruits',
    favorite: false,
    price: 15,
    weight: '1 kg',
    quantity: 10,
    image: './assets/Vegetables&Fruits/FreshVegetables/tomato.jpg',
    hey: false,
  },
  {
    id: '3',
    name: 'Onion',
    category: 'Fresh Vegetables',
    tag: 'Vegetables & Fruits',
    favorite: false,
    price: 26,
    weight: '1 kg',
    quantity: 10,
    image: './assets/Vegetables&Fruits/FreshVegetables/onion.jpg',
    hey: false,
  },
  {
    id: '4',
    name: 'Carrot',
    category: 'Fresh Vegetables',
    tag: 'Vegetables & Fruits',
    favorite: false,
    price: 28,
    weight: '500 g',
    quantity: 10,
    image: './assets/Vegetables&Fruits/FreshVegetables/carrot.jpg',
    hey: false,
  },
  {
    id: '5',
    name: 'Beetroot',
    category: 'Fresh Vegetables',
    tag: 'Vegetables & Fruits',
    favorite: false,
    price: 15,
    weight: '500 g',
    quantity: 10,
    image: './assets/Vegetables&Fruits/FreshVegetables/beetroot.jpg',
    hey: false,
  },
  // {
  //   id: '6',
  //   name: 'Banana',
  //   category: 'Fresh Fruits',
  //   tag: 'Vegetables & Fruits',
  //   favorite: false,
  //   price: 30,
  //   details: [{ weight: '3 pieces', quantity: 10, price: 30 }],
  //   image: './assets/Vegetables&Fruits/FreshFruits/banana.jpg',
  // },
  // {
  //   id: '7',
  //   name: 'Kinnow',
  //   category: 'Fresh Fruits',
  //   tag: 'Vegetables & Fruits',
  //   favorite: false,
  //   price: 50,
  //   details: [{ weight: '500 g', quantity: 10, price: 50 }],
  //   image: './assets/Vegetables&Fruits/FreshFruits/kinnow.jpg',
  // },
  // {
  //   id: '8',
  //   name: 'Green Grapes',
  //   category: 'Fresh Fruits',
  //   tag: 'Vegetables & Fruits',
  //   favorite: false,
  //   price: 79,
  //   details: [{ weight: '500 g', quantity: 10, price: 79 }],
  //   image: './assets/Vegetables&Fruits/FreshFruits/green-grapes.jpg',
  // },
  // {
  //   id: '9',
  //   name: 'Sapota',
  //   category: 'Fresh Fruits',
  //   tag: 'Vegetables & Fruits',
  //   favorite: false,
  //   price: 45,
  //   details: [{ weight: '500 g', quantity: 10, price: 45 }],
  //   image: './assets/Vegetables&Fruits/FreshFruits/sapots.jpg',
  // },
  // {
  //   id: '10',
  //   name: 'Kiwi',
  //   category: 'Fresh Fruits',
  //   tag: 'Vegetables & Fruits',
  //   favorite: false,
  //   price: 132,
  //   details: [{ weight: '3 pieces', quantity: 10, price: 132 }],
  //   image: './assets/Vegetables&Fruits/FreshFruits/kiwi.jpg',
  // },
  // {
  //   id: '11',
  //   name: "Kellogg's Corn Flakes With Real Honey",
  //   category: 'Breakfast Cereal',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 160,
  //   details: [{ weight: '300 g', quantity: 10, price: 160 }],
  //   image:
  //     './assets/Dairy&Breakfast/BreakfastCereal/Kelloggs-Corn-Flakes-With-Real-Honey.jpg',
  // },
  // {
  //   id: '12',
  //   name: "Kellogg's Original Cereals Corn Flakes",
  //   category: 'Breakfast Cereal',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 205,
  //   details: [{ weight: '475 g', quantity: 10, price: 205 }],
  //   image:
  //     './assets/Dairy&Breakfast/BreakfastCereal/Kelloggs-Original-Cereals-Corn-Flakes.jpg',
  // },
  // {
  //   id: '13',
  //   name: "Kellogg's Special K Cereal",
  //   category: 'Breakfast Cereal',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 238,
  //   details: [{ weight: '455 g', quantity: 10, price: 238 }],
  //   image:
  //     './assets/Dairy&Breakfast/BreakfastCereal/Kelloggs-Special-K-Cereal.jpg',
  // },
  // {
  //   id: '14',
  //   name: 'Quaker Rolled Oats',
  //   category: 'Breakfast Cereal',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 79,
  //   details: [{ weight: '400 g', quantity: 10, price: 79 }],
  //   image: './assets/Dairy&Breakfast/BreakfastCereal/quaker-rolled-oats.jpg',
  // },
  // {
  //   id: '15',
  //   name: 'Saffola Classic Masala Oats',
  //   category: 'Breakfast Cereal',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 16,
  //   details: [{ weight: '38 g', quantity: 10, price: 16 }],
  //   image:
  //     './assets/Dairy&Breakfast/BreakfastCereal/saffola-classic-masala-oats.jpg',
  // },
  // {
  //   id: '16',
  //   name: 'Amul Taaza Homogenised Toned Milk',
  //   category: 'Milk',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 72,
  //   details: [{ weight: '1 L', quantity: 10, price: 72 }],
  //   image: './assets/Dairy&Breakfast/Milk/amul-taza-homogenised-toned-milk.jpg',
  // },
  // {
  //   id: '17',
  //   name: 'Chitale Pasteurised Cow Fresh Milk',
  //   category: 'Milk',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 27,
  //   details: [{ weight: '500 ml', quantity: 10, price: 27 }],
  //   image: './assets/Dairy&Breakfast/Milk/chitale-cow-milk.jpg',
  // },
  // {
  //   id: '18',
  //   name: 'Chitale Full Cream Fresh Milk',
  //   category: 'Milk',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 35,
  //   details: [{ weight: '500 ml', quantity: 10, price: 35 }],
  //   image: './assets/Dairy&Breakfast/Milk/chitale-full-cream-milk.jpg',
  // },
  // {
  //   id: '19',
  //   name: 'Go Supremo Cow Milk',
  //   category: 'Milk',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 76,
  //   details: [{ weight: '1 L', quantity: 10, price: 76 }],
  //   image: './assets/Dairy&Breakfast/Milk/go-supremo-cow-milk.jpg',
  // },
  // {
  //   id: '20',
  //   name: 'Yakult Probiotic Health Drink',
  //   category: 'Milk',
  //   tag: 'Dairy & Breakfast',
  //   favorite: false,
  //   price: 80,
  //   details: [{ weight: '65 ml', quantity: 10, price: 80 }],
  //   image: './assets/Dairy&Breakfast/Milk/yakult-probiotic-health-drink.jpg',
  // },
  // {
  //   id: '21',
  //   name: 'Maaza Mango Drink 1.2 l',
  //   category: 'Fruit Juices',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 70,
  //   details: [{ weight: '1.2 L', quantity: 10, price: 70 }],
  //   image:
  //     './assets/ColdDrinks&Juices/FruitsJuices/Maaza-Mango-Drink-1.2-l.jpg',
  // },
  // {
  //   id: '22',
  //   name: 'Real Fruit Power Cranberry Juice',
  //   category: 'Fruit Juices',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 111,
  //   details: [{ weight: '1 L', quantity: 10, price: 111 }],
  //   image:
  //     './assets/ColdDrinks&Juices/FruitsJuices/Real-Fruit-Power-Cranberry-Juice.jpg',
  // },
  // {
  //   id: '23',
  //   name: 'Real Fruit Power Litchi Juice',
  //   category: 'Fruit Juices',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 103,
  //   details: [{ weight: '1 L', quantity: 10, price: 103 }],
  //   image:
  //     './assets/ColdDrinks&Juices/FruitsJuices/Real-Fruit-Power-Litchi-Juice.jpg',
  // },
  // {
  //   id: '24',
  //   name: 'Real Fruit Power Orange Juice',
  //   category: 'Fruit Juices',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 105,
  //   details: [{ weight: '1 L', quantity: 10, price: 105 }],
  //   image:
  //     './assets/ColdDrinks&Juices/FruitsJuices/Real-Fruit-Power-Orange-Juice.jpg',
  // },
  // {
  //   id: '25',
  //   name: 'Slice Thickest Mango Drink',
  //   category: 'Fruit Juices',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 40,
  //   details: [{ weight: '600 ml', quantity: 10, price: 40 }],
  //   image:
  //     './assets/ColdDrinks&Juices/FruitsJuices/Slice-Thickest-Mango-Drink.jpg',
  // },
  // {
  //   id: '26',
  //   name: 'Coca-Cola Soft Drink (750 ml)',
  //   category: 'Soft Drinks',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 40,
  //   details: [{ weight: '750 ml', quantity: 10, price: 40 }],
  //   image:
  //     './assets/ColdDrinks&Juices/SoftDrinks/Coca-Cola-Soft-Drink-(750 ml).jpg',
  // },
  // {
  //   id: '27',
  //   name: 'Mountain Dew Grip Soft Drink',
  //   category: 'Soft Drinks',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 33,
  //   details: [{ weight: '750 ml', quantity: 10, price: 33 }],
  //   image:
  //     './assets/ColdDrinks&Juices/SoftDrinks/Mountain-Dew-Grip-Soft-Drink.jpg',
  // },
  // {
  //   id: '28',
  //   name: 'Mountain Dew Soft Drink',
  //   category: 'Soft Drinks',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 34,
  //   details: [{ weight: '250 ml', quantity: 10, price: 34 }],
  //   image: './assets/ColdDrinks&Juices/SoftDrinks/Mountain-Dew-Soft-Drink.jpg',
  // },
  // {
  //   id: '29',
  //   name: 'Sprite Lime Flavored Soft Drink 750 ml',
  //   category: 'Soft Drinks',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 40,
  //   details: [{ weight: '750 ml', quantity: 10, price: 40 }],
  //   image:
  //     './assets/ColdDrinks&Juices/SoftDrinks/Sprite-Lime-Flavored-Soft-Drink-750ml.jpg',
  // },
  // {
  //   id: '30',
  //   name: 'Thums Up Soft Drink (750 ml)',
  //   category: 'Soft Drinks',
  //   tag: 'Cold Drinks & Juices ',
  //   favorite: false,
  //   price: 40,
  //   details: [{ weight: '750 ml', quantity: 10, price: 40 }],
  //   image:
  //     './assets/ColdDrinks&Juices/SoftDrinks/Thums-Up-Soft-Drink-(750 ml).jpg',
  // },
];
